### PR TITLE
IAV-1189: Add visited links color

### PR DESCRIPTION
**Pull request by kallevu**

### CODE REVIEW

**Comment by lauriii** [comment]
Could we add a link example to the styleguide? This is not visible anywhere now

**Comment by kallevu** [comment]
@lauriii Should we do that by adding colours, they are not in styleguide? If we use links, how we should apply `:visited` styles?

**Comment by lauriii** [comment]
We can do the same as we've done with the :hover here: https://github.com/LaakarikeskusAava/styleguide/blob/master/styles/components/buttons/buttons.scss

**Comment by juhog** [comment]
I added the visited pseudo-class thingy in this commit: https://github.com/LaakarikeskusAava/styleguide/pull/15/commits/437ea295e46f13751bbf2022bbb1d808582e9eb8

screen shot 2017-03-21 at 09 22 01

**Review by juhog — APPROVED** [review]

**Review by lauriii — APPROVED** [review]

**Pull request merged**
